name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  AZURE_BASE_URL:
    description: "Azure OpenAI base url."
    required: true
  AZURE_API_KEY:
    description: "Azure OpenAI API key."
    required: true
  AZURE_API_VERSION:
    description: "Azure OpenAI API version."
    required: true
  AZURE_DEPLOYMENT_NAME:
    description: "Azure OpenAI deployment name."
    required: true
  exclude:
    description: "Glob patterns to exclude files from the diff analysis."
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
